// @generated by PolyXML Compiler (https://github.com/polyxml/PolyXML)
#![allow(dead_code, unused_imports, unused_mut, unused_variables, unused_assignments, non_camel_case_types, non_snake_case)]

use std::borrow::Cow;
use serde::{Deserialize, Serialize};
use std::str::FromStr;
use quick_xml::events::{BytesEnd, BytesStart, BytesText, Event};
use quick_xml::{Reader, Writer};
use polyxml::{PolyXmlError, Result};

#[allow(dead_code)]
pub(crate) fn skip_xml_element(reader: &mut Reader<&[u8]>) -> Result<()> {
    let mut depth = 1;
    loop {
        match reader.read_event()? {
            Event::Start(_) => depth += 1,
            Event::End(_) => {
                depth -= 1;
                if depth == 0 {
                    break;
                }
            }
            Event::Eof => break,
            _ => {}
        }
    }
    Ok(())
}

#[allow(dead_code)]
pub(crate) fn read_element_text<'a>(reader: &mut Reader<&'a [u8]>, tag_name: &str) -> Result<Cow<'a, str>> {
    let mut text = Cow::Borrowed("");
    loop {
        match reader.read_event()? {
            Event::Text(t) => {
                let raw = match t.into_inner() {
                    Cow::Borrowed(b) => match quick_xml::escape::unescape(b)? {
                        Cow::Borrowed(s) => Cow::Borrowed(s),
                        Cow::Owned(s) => Cow::Owned(s),
                    },
                    Cow::Owned(s) => Cow::Owned(quick_xml::escape::unescape(&s)?.into_owned()),
                };
                if text.is_empty() {
                    text = raw;
                } else {
                    text.to_mut().push_str(&raw);
                }
            }
            Event::CData(c) => {
                text.to_mut().push_str(c.as_ref());
            }
            Event::GeneralRef(r) => {
                if r.is_char_ref() {
                    if let Some(ch) = r.resolve_char_ref()? {
                        text.to_mut().push(ch);
                    }
                } else if let Some(val) = quick_xml::escape::resolve_xml_entity(r.as_ref()) {
                    text.to_mut().push_str(val);
                } else {
                    text.to_mut().push_str(r.as_ref());
                }
            }
            Event::End(e) if e.local_name().as_ref() == tag_name => break,
            Event::Eof => break,
            _ => {}
        }
    }
    Ok(text)
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "R&D")]
    #[default]
    Rd,
    #[serde(rename = ""quoted" 'value' <tag>")]
    QuotedValueTag,
    #[serde(rename = "café 😀")]
    Café,
    #[serde(rename = "literal &amp;")]
    LiteralAmp,
    #[serde(rename = "slash\path\u000a")]
    SlashPathU000a,
    #[serde(rename = "tab	line
carriagetail")]
    TabLineCarriageTail,
    #[serde(rename = "next line")]
    NextLine,
}

impl Status {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Rd => "R&D",
            Self::QuotedValueTag => ""quoted" 'value' <tag>",
            Self::Café => "café 😀",
            Self::LiteralAmp => "literal &amp;",
            Self::SlashPathU000a => "slash\path\u000a",
            Self::TabLineCarriageTail => "tab	line
carriagetail",
            Self::NextLine => "next line",
        }
    }
}

impl std::str::FromStr for Status {
    type Err = String;

    fn from_str(s: &str) -> std::result::Result<Self, Self::Err> {
        match s {
            "R&D" => Ok(Self::Rd),
            ""quoted" 'value' <tag>" => Ok(Self::QuotedValueTag),
            "café 😀" => Ok(Self::Café),
            "literal &amp;" => Ok(Self::LiteralAmp),
            "slash\path\u000a" => Ok(Self::SlashPathU000a),
            "tab	line
carriagetail" => Ok(Self::TabLineCarriageTail),
            "next line" => Ok(Self::NextLine),
            _ => Err(format!("Unknown Status variant: {}", s)),
        }
    }
}

impl std::fmt::Display for Status {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}
