// @generated by PolyXML Compiler (https://github.com/polyxml/PolyXML)
#![allow(dead_code, unused_imports, unused_mut, unused_variables, unused_assignments, non_camel_case_types, non_snake_case)]

use std::borrow::Cow;
use serde::{Deserialize, Serialize};
use std::str::FromStr;
use quick_xml::events::{BytesEnd, BytesStart, BytesText, Event};
use quick_xml::{Reader, Writer};
use polyxml::{PolyXmlError, Result};

#[allow(dead_code)]
pub(crate) fn skip_xml_element(reader: &mut Reader<&[u8]>) -> Result<()> {
    let mut depth = 1;
    loop {
        match reader.read_event()? {
            Event::Start(_) => depth += 1,
            Event::End(_) => {
                depth -= 1;
                if depth == 0 {
                    break;
                }
            }
            Event::Eof => break,
            _ => {}
        }
    }
    Ok(())
}

#[allow(dead_code)]
pub(crate) fn read_element_text<'a>(reader: &mut Reader<&'a [u8]>, tag_name: &str) -> Result<Cow<'a, str>> {
    let mut text = Cow::Borrowed("");
    loop {
        match reader.read_event()? {
            Event::Text(t) => {
                let raw = match t.into_inner() {
                    Cow::Borrowed(b) => match quick_xml::escape::unescape(b)? {
                        Cow::Borrowed(s) => Cow::Borrowed(s),
                        Cow::Owned(s) => Cow::Owned(s),
                    },
                    Cow::Owned(s) => Cow::Owned(quick_xml::escape::unescape(&s)?.into_owned()),
                };
                if text.is_empty() {
                    text = raw;
                } else {
                    text.to_mut().push_str(&raw);
                }
            }
            Event::CData(c) => {
                text.to_mut().push_str(c.as_ref());
            }
            Event::GeneralRef(r) => {
                if r.is_char_ref() {
                    if let Some(ch) = r.resolve_char_ref()? {
                        text.to_mut().push(ch);
                    }
                } else if let Some(val) = quick_xml::escape::resolve_xml_entity(r.as_ref()) {
                    text.to_mut().push_str(val);
                } else {
                    text.to_mut().push_str(r.as_ref());
                }
            }
            Event::End(e) if e.local_name().as_ref() == tag_name => break,
            Event::Eof => break,
            _ => {}
        }
    }
    Ok(text)
}

pub type Code<'a> = Cow<'a, str>;
pub fn validate_Code_patterns(value: &str) -> std::result::Result<(), &'static str> {
    static PATTERN_0: std::sync::OnceLock<std::result::Result<regex::Regex, regex::Error>> = std::sync::OnceLock::new();
    let pattern = PATTERN_0.get_or_init(|| regex::Regex::new("\\A(?:[A-Z]&[A-Z])\\z")).as_ref().map_err(|_| "unsupported pattern syntax")?;
    if !pattern.is_match(value) { return Err("pattern constraint failed"); }
    Ok(())
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "R&D")]
    #[default]
    Rd,
    #[serde(rename = ""quoted" 'value' <tag>")]
    QuotedValueTag,
    #[serde(rename = "café 😀")]
    Café,
    #[serde(rename = "literal &amp;")]
    LiteralAmp,
}

impl Status {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Rd => "R&D",
            Self::QuotedValueTag => ""quoted" 'value' <tag>",
            Self::Café => "café 😀",
            Self::LiteralAmp => "literal &amp;",
        }
    }
}

impl std::str::FromStr for Status {
    type Err = String;

    fn from_str(s: &str) -> std::result::Result<Self, Self::Err> {
        match s {
            "R&D" => Ok(Self::Rd),
            ""quoted" 'value' <tag>" => Ok(Self::QuotedValueTag),
            "café 😀" => Ok(Self::Café),
            "literal &amp;" => Ok(Self::LiteralAmp),
            _ => Err(format!("Unknown Status variant: {}", s)),
        }
    }
}

impl std::fmt::Display for Status {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct RootType<'a> {
    #[serde(rename = "Status")]
    pub status: Status,
    #[serde(rename = "Code")]
    pub code: Code<'a>,
    #[serde(rename = "Fixed")]
    pub fixed: Cow<'a, str>,
    #[serde(rename = "Default")]
    pub default: Cow<'a, str>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub label: Option<Cow<'a, str>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mode: Option<Cow<'a, str>>,
}

impl<'a> RootType<'a> {
    pub fn from_xml(xml: &'a str) -> Result<Self>
    {
        let mut reader = Reader::from_str(xml);
        loop {
            match reader.read_event()? {
                Event::Start(e) => return Self::decode_xml(&mut reader, &e),
                Event::Empty(e) => return Self::decode_xml_empty(&e),
                Event::Eof => break,
                _ => {}
            }
        }
        Err(PolyXmlError::SchemaError("Unexpected EOF while parsing RootType".into()))
    }

    pub fn from_xml_bytes(xml_bytes: &'a [u8]) -> Result<Self>
    {
        let s = std::str::from_utf8(xml_bytes)?;
        Self::from_xml(s)
    }

    pub fn decode_xml(reader: &mut Reader<&'a [u8]>, start: &BytesStart<'_>) -> Result<Self>
    {
        let mut var_status = None;
        let mut var_code = None;
        let mut var_fixed = None;
        let mut var_default = None;
        let mut var_label = None;
        let mut var_mode = None;

        for attr in start.attributes() {
            let attr = attr?;
            match attr.key.local_name().as_ref() {
                "label" => {
                    let s = attr.value.as_ref();
                    let val: Cow<'_, str> = match quick_xml::escape::unescape(s)? {
                        Cow::Borrowed(s) => Cow::Owned(s.to_string()),
                        Cow::Owned(s) => Cow::Owned(s),
                    };
                    var_label = Some(val);
                }
                "mode" => {
                    let s = attr.value.as_ref();
                    let val: Cow<'_, str> = match quick_xml::escape::unescape(s)? {
                        Cow::Borrowed(s) => Cow::Owned(s.to_string()),
                        Cow::Owned(s) => Cow::Owned(s),
                    };
                    var_mode = Some(val);
                }
                _ => {}
            }
        }

        loop {
            match reader.read_event()? {
                Event::Start(e) => match e.local_name().as_ref() {
                    "Status" => {
                        let text = read_element_text(reader, "Status")?;
                        let s = text.trim();
                        let val = Status::from_str(s).map_err(|_| PolyXmlError::ScalarParseError { field: "status".into(), expected: "Status", value: s.into() })?;
                        var_status = Some(val);
                    }
                    "Code" => {
                        let text = read_element_text(reader, "Code")?;
        validate_Code_patterns(&text).map_err(|message| PolyXmlError::FacetViolation { field: "code".into(), expected: message.into(), actual: (&text).to_string() })?;
                        var_code = Some(text);
                    }
                    "Fixed" => {
                        let text = read_element_text(reader, "Fixed")?;
                        var_fixed = Some(text);
                    }
                    "Default" => {
                        let text = read_element_text(reader, "Default")?;
                        var_default = Some(text);
                    }
                    _ => {
                        skip_xml_element(reader)?;
                    }
                },
                Event::Empty(e) => match e.local_name().as_ref() {
                    "Status" => {
                    }
                    "Code" => {
        validate_Code_patterns("").map_err(|message| PolyXmlError::FacetViolation { field: "code".into(), expected: message.into(), actual: ("").to_string() })?;
                        var_code = Some(Cow::Borrowed(""));
                    }
                    "Fixed" => {
                        var_fixed = Some(Cow::Borrowed(""));
                    }
                    "Default" => {
                        var_default = Some(Cow::Borrowed(""));
                    }
                    _ => {}
                },
                Event::End(e) if e.local_name().as_ref() == start.local_name().as_ref() => break,
                Event::Eof => break,
                _ => {}
            }
        }

        let value = Self {
            status: var_status.ok_or_else(|| PolyXmlError::SchemaError("Missing required field 'Status'".into()))?,
            code: var_code.ok_or_else(|| PolyXmlError::SchemaError("Missing required field 'Code'".into()))?,
            fixed: var_fixed.ok_or_else(|| PolyXmlError::SchemaError("Missing required field 'Fixed'".into()))?,
            default: var_default.ok_or_else(|| PolyXmlError::SchemaError("Missing required field 'Default'".into()))?,
            label: var_label,
            mode: var_mode,
        };
        value.validate_patterns()?;
        Ok(value)
    }

    pub fn decode_xml_empty(start: &BytesStart<'_>) -> Result<Self> {
        let mut var_status = None;
        let mut var_code = None;
        let mut var_fixed = None;
        let mut var_default = None;
        let mut var_label = None;
        let mut var_mode = None;

        for attr in start.attributes() {
            let attr = attr?;
            match attr.key.local_name().as_ref() {
                "label" => {
                    let s = attr.value.as_ref();
                    let val: Cow<'_, str> = match quick_xml::escape::unescape(s)? {
                        Cow::Borrowed(s) => Cow::Owned(s.to_string()),
                        Cow::Owned(s) => Cow::Owned(s),
                    };
                    var_label = Some(val);
                }
                "mode" => {
                    let s = attr.value.as_ref();
                    let val: Cow<'_, str> = match quick_xml::escape::unescape(s)? {
                        Cow::Borrowed(s) => Cow::Owned(s.to_string()),
                        Cow::Owned(s) => Cow::Owned(s),
                    };
                    var_mode = Some(val);
                }
                _ => {}
            }
        }

        let value = Self {
            status: var_status.unwrap_or_default(),
            code: var_code.unwrap_or(Cow::Borrowed("")),
            fixed: var_fixed.unwrap_or(Cow::Borrowed("")),
            default: var_default.unwrap_or(Cow::Borrowed("")),
            label: var_label,
            mode: var_mode,
        };
        value.validate_patterns()?;
        Ok(value)
    }

    pub fn to_xml(&self) -> Result<Vec<u8>> {
        let mut buf = Vec::new();
        let mut writer = Writer::new(std::io::Cursor::new(&mut buf));
        self.encode_xml(&mut writer, None)?;
        Ok(buf)
    }

    pub fn to_xml_string(&self) -> Result<String> {
        let bytes = self.to_xml()?;
        String::from_utf8(bytes).map_err(|e| PolyXmlError::Utf8Error(e.utf8_error()))
    }

    pub fn from_json_str(json_str: &'a str) -> std::result::Result<Self, serde_json::Error>
    {
        serde_json::from_str(json_str)
    }

    pub fn from_json_slice(bytes: &'a [u8]) -> std::result::Result<Self, serde_json::Error>
    {
        serde_json::from_slice(bytes)
    }

    pub fn to_json_string(&self) -> std::result::Result<String, serde_json::Error> {
        serde_json::to_string(self)
    }

    pub fn to_json_vec(&self) -> std::result::Result<Vec<u8>, serde_json::Error> {
        serde_json::to_vec(self)
    }

    pub fn validate_patterns(&self) -> Result<()> {
        validate_Code_patterns(&self.code.to_string()).map_err(|message| PolyXmlError::FacetViolation { field: "code".into(), expected: message.into(), actual: (&self.code.to_string()).to_string() })?;
        Ok(())
    }
    pub fn encode_xml<W: std::io::Write>(&self, writer: &mut Writer<W>, tag_name: Option<&str>) -> Result<()> {
        self.validate_patterns()?;
        let tag = tag_name.unwrap_or("RootType");
        let mut start = BytesStart::new(tag);
        if let Some(ref val) = self.label {
            start.push_attribute(("label", val.as_ref()));
        }
        if let Some(ref val) = self.mode {
            start.push_attribute(("mode", val.as_ref()));
        }
        writer.write_event(Event::Start(start))?;
        writer.write_event(Event::Start(BytesStart::new("Status")))?;
        writer.write_event(Event::Text(BytesText::new(self.status.as_str())))?;
        writer.write_event(Event::End(BytesEnd::new("Status")))?;
        writer.write_event(Event::Start(BytesStart::new("Code")))?;
        writer.write_event(Event::Text(BytesText::new(self.code.as_ref())))?;
        writer.write_event(Event::End(BytesEnd::new("Code")))?;
        writer.write_event(Event::Start(BytesStart::new("Fixed")))?;
        writer.write_event(Event::Text(BytesText::new(self.fixed.as_ref())))?;
        writer.write_event(Event::End(BytesEnd::new("Fixed")))?;
        writer.write_event(Event::Start(BytesStart::new("Default")))?;
        writer.write_event(Event::Text(BytesText::new(self.default.as_ref())))?;
        writer.write_event(Event::End(BytesEnd::new("Default")))?;
        writer.write_event(Event::End(BytesEnd::new(tag)))?;
        Ok(())
    }
}

pub type Root<'a> = RootType<'a>;
