[package]
name = "polyxml-c"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
readme = "README.md"
description = "Standard C-ABI shared library and headers for PolyXML"

[lib]
name = "polyxml"
crate-type = ["cdylib", "staticlib"]

[dependencies]
polyxml = { path = "../polyxml-core", version = "0.30.6" }
