// @generated by PolyXML Compiler (https://github.com/polyxml/PolyXML)
#![allow(dead_code, unused_imports, unused_mut, unused_variables, unused_assignments, non_camel_case_types, non_snake_case)]

use std::borrow::Cow;
use serde::{Deserialize, Serialize};
use std::str::FromStr;
use quick_xml::events::{BytesEnd, BytesStart, BytesText, Event};
use quick_xml::{Reader, Writer};
use polyxml::{PolyXmlError, Result};

#[allow(dead_code)]
pub(crate) fn skip_xml_element(reader: &mut Reader<&[u8]>) -> Result<()> {
    let mut depth = 1;
    loop {
        match reader.read_event()? {
            Event::Start(_) => depth += 1,
            Event::End(_) => {
                depth -= 1;
                if depth == 0 {
                    break;
                }
            }
            Event::Eof => break,
            _ => {}
        }
    }
    Ok(())
}

#[allow(dead_code)]
pub(crate) fn read_element_text<'a>(reader: &mut Reader<&'a [u8]>, tag_name: &str) -> Result<Cow<'a, str>> {
    let mut text = Cow::Borrowed("");
    loop {
        match reader.read_event()? {
            Event::Text(t) => {
                let raw = match t.into_inner() {
                    Cow::Borrowed(b) => match quick_xml::escape::unescape(b)? {
                        Cow::Borrowed(s) => Cow::Borrowed(s),
                        Cow::Owned(s) => Cow::Owned(s),
                    },
                    Cow::Owned(s) => Cow::Owned(quick_xml::escape::unescape(&s)?.into_owned()),
                };
                if text.is_empty() {
                    text = raw;
                } else {
                    text.to_mut().push_str(&raw);
                }
            }
            Event::CData(c) => {
                text.to_mut().push_str(c.as_ref());
            }
            Event::GeneralRef(r) => {
                if r.is_char_ref() {
                    if let Some(ch) = r.resolve_char_ref()? {
                        text.to_mut().push(ch);
                    }
                } else if let Some(val) = quick_xml::escape::resolve_xml_entity(r.as_ref()) {
                    text.to_mut().push_str(val);
                } else {
                    text.to_mut().push_str(r.as_ref());
                }
            }
            Event::End(e) if e.local_name().as_ref() == tag_name => break,
            Event::Eof => break,
            _ => {}
        }
    }
    Ok(text)
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "R&amp;D")]
    #[default]
    RAmpD,
    #[serde(rename = "&quot;quoted&quot; &apos;value&apos; &lt;tag&gt;")]
    QuotQuotedQuotAposValueAposLtTagGt,
    #[serde(rename = "caf&#xE9; &#128512;")]
    CafHashxE9Hash128512,
    #[serde(rename = "literal &amp;amp;")]
    LiteralAmpAmp,
    #[serde(rename = "slash\path\u000a")]
    SlashPathU000a,
    #[serde(rename = "tab&#9;line&#10;carriage&#13;tail")]
    TabHash9LineHash10CarriageHash13Tail,
    #[serde(rename = "&#x85;next&#x2028;line")]
    Hashx85NextHashx2028Line,
}

impl Status {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::RAmpD => "R&amp;D",
            Self::QuotQuotedQuotAposValueAposLtTagGt => "&quot;quoted&quot; &apos;value&apos; &lt;tag&gt;",
            Self::CafHashxE9Hash128512 => "caf&#xE9; &#128512;",
            Self::LiteralAmpAmp => "literal &amp;amp;",
            Self::SlashPathU000a => "slash\path\u000a",
            Self::TabHash9LineHash10CarriageHash13Tail => "tab&#9;line&#10;carriage&#13;tail",
            Self::Hashx85NextHashx2028Line => "&#x85;next&#x2028;line",
        }
    }
}

impl std::str::FromStr for Status {
    type Err = String;

    fn from_str(s: &str) -> std::result::Result<Self, Self::Err> {
        match s {
            "R&amp;D" => Ok(Self::RAmpD),
            "&quot;quoted&quot; &apos;value&apos; &lt;tag&gt;" => Ok(Self::QuotQuotedQuotAposValueAposLtTagGt),
            "caf&#xE9; &#128512;" => Ok(Self::CafHashxE9Hash128512),
            "literal &amp;amp;" => Ok(Self::LiteralAmpAmp),
            "slash\path\u000a" => Ok(Self::SlashPathU000a),
            "tab&#9;line&#10;carriage&#13;tail" => Ok(Self::TabHash9LineHash10CarriageHash13Tail),
            "&#x85;next&#x2028;line" => Ok(Self::Hashx85NextHashx2028Line),
            _ => Err(format!("Unknown Status variant: {}", s)),
        }
    }
}

impl std::fmt::Display for Status {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}
